In [2]:
import pandas as pd
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

In [3]:
df = pd.read_csv('prepped_churn_data.csv', index_col='Customer_ID')
df

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,totalCharges_tenure_ratio
Customer_ID,,,,,,,,
0,1,0,0,0,29.85,29.85,0,29.850000
1,34,1,1,1,56.95,1889.50,0,55.573529
2,2,1,0,1,53.85,108.15,1,54.075000
3,45,0,1,2,42.30,1840.75,0,40.905556
4,2,1,0,0,70.70,151.65,1,75.825000
...,...,...,...,...,...,...,...,...
7038,24,1,1,1,84.80,1990.50,0,82.937500
7039,72,1,1,3,103.20,7362.90,0,102.262500
7040,11,0,0,0,29.60,346.45,0,31.495455
7041,4,1,0,1,74.40,306.60,1,76.650000
7042,66,1,2,2,105.65,6844.50,0,103.704545

In [4]:
automl = setup(df, target = 'Churn')

In [6]:
best_model = compare_models()

Processing:   0%|          | 0/61 [00:00<?, ?it/s]

In [7]:
predict_model(best_model, df.iloc[-2:-1])

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,totalCharges_tenure_ratio,Churn,Label,Score
Customer_ID,,,,,,,,,,
7041,4.0,1.0,0.0,1.0,74.400002,306.600006,76.650002,1,1,0.5746

In [8]:
save_model(best_model, 'LR')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=/tmp/joblib),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None, include=['tenure', 'PhoneService', 'Contract', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'totalCharges_tenure_ratio'], transformer=SimpleImputer(add_indicator=False, copy=True, fill_value=None, missing_values=nan, strategy='mean', verbose=0))),
                 ('ca...
                  TransformerWrapper(exclude=None, include=[], transformer=SimpleImputer(add_indicator=False, copy=True, fill_value='constant', missing_values=nan, strategy='constant', verbose=0))),
                 ['trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=2946,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False)]],
          verbose=False), 'LR.pkl')